# Generated by Django 4.1.5 on 2023-01-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_slider_slider_misc_slider_publish_815c0a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('image1', models.ImageField(upload_to='company')),
                ('image2', models.ImageField(upload_to='company')),
                ('image3', models.ImageField(upload_to='company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
