# Generated by Django 4.1.5 on 2023-01-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_aboutcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('title1', models.CharField(max_length=20)),
                ('text1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=20)),
                ('text2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=20)),
                ('text3', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
